from tkinter import *
from PIL import ImageTk, Image
import module1
x = 0

str1 = "You and a your dog lucky are gathered around a campfire deep in the woods...\n When you wake up you notice you are alone, lucky is nowhere to be found"
str2 = "First you look for lucky in a nearby abandoned village but, something seems odd...."
str3 = "As you venture deeper into the woods you get the feeling your not alone."
str4 = "The deep fog makes you feel like your walking in circles..."
str5 = "You hear a faint cry....could that be lucky?"
str6 = "Do you choose to enter deeper into the unknown?"
def next():
    global x
    x+=1
    window.destroy()
    window.mainloop()

def quit():
    window.destroy()
    exit(1)

if(x==0):
    window = Tk()
    window.minsize(768,768)
    window.title("Biome Runner")
    window.resizable(False,False)
    photo = PhotoImage(file=f"{x}.png")
    background_label = Label(window, image = photo)
    background_label.pack(fill=BOTH, expand=1)
    label2 = Label(window, text = f"Streaks: {module1.streak}", font="Ariel", anchor="n",bg="black", fg="white")
    label2.place(relx=.5, rely=.04, anchor="s")
    button_next = Button(window, text="Start!", bg="black",font=("Ariel", 20, "bold"), fg="white", command=next)
    button_next.place(relx=0.5, rely=.45, anchor="n")
    exitbutton = Button(window, text='Quit!', command=quit,bg="black", fg = "white", font=("Ariel", 20, "bold"))
    exitbutton.place(relx=.5,rely=.95,anchor= "s")
    window.mainloop()
if(x==1):
    window = Tk()
    window.minsize(768,768)
    window.resizable(False,False)
    window.title("Biome Runner")
    photo = PhotoImage(file=f"{x}.png")
    background_label = Label(window, image = photo)
    background_label.pack(fill=BOTH, expand=1)
    label2 = Label(window, text = f"{str1}", font=("Ariel",15,"bold"), anchor="n",bg="black", fg="white")
    label2.place(relx=.5, rely=.2, anchor="s")
    button_next = Button(window, text="Next!", bg="black",font=("Ariel", 20, "bold"), fg="white", command=next)
    button_next.place(relx=.8, rely=.95, anchor="sw")
    label3 = Label(window, text = "Distance remaining: .25 Miles", font=("Ariel",10,"bold"), anchor="n",bg="black", fg="white")
    label3.place(relx=.5, rely=.95, anchor="s")
    exitbutton = Button(window, text='Quit!', command=quit,bg="black", fg = "white", font=("Ariel", 20, "bold"))
    exitbutton.place(relx=.15,rely=.95,anchor= "s")
    window.mainloop()
if(x==2):
    window = Tk()
    window.minsize(768,768)
    window.title("Biome Runner")
    window.resizable(False,False)
    photo = PhotoImage(file=f"{x}.png")
    background_label = Label(window, image = photo)
    background_label.pack(fill=BOTH, expand=1)
    label2 = Label(window, text = f"{str2}", font=("Ariel",13,"bold"), anchor="n",bg="black", fg="white")
    label2.place(relx=.5, rely=.2, anchor="s")
    button_next = Button(window, text="Next!", bg="black",font=("Ariel", 20, "bold"), fg="white", command=next)
    button_next.place(relx=.8, rely=.95, anchor="sw")
    label3 = Label(window, text = "Distance remaining: .25 Miles", font=("Ariel",10,"bold"), anchor="n",bg="black", fg="white")
    label3.place(relx=.5, rely=.95, anchor="s")
    exitbutton = Button(window, text='Quit!', command=quit,bg="black", fg = "white", font=("Ariel", 20, "bold"))
    exitbutton.place(relx=.15,rely=.95,anchor= "s")
    window.mainloop()
if(x==3):
    window = Tk()
    window.minsize(768,768)
    window.resizable(False,False)
    window.title("Biome Runner")
    photo = PhotoImage(file=f"{x}.png")
    background_label = Label(window, image = photo)
    background_label.pack(fill=BOTH, expand=1)
    label2 = Label(window, text = f"{str3}",font=("Ariel",15,"bold"), anchor="n",bg="black", fg="white")
    label2.place(relx=.5, rely=.2, anchor="s")
    button_next = Button(window, text="Next!", bg="black",font=("Ariel", 20, "bold"), fg="white", command=next)
    button_next.place(relx=.8, rely=.95, anchor="sw")
    label3 = Label(window, text = "Distance remaining: .25 Miles", font=("Ariel",10,"bold"), anchor="n",bg="black", fg="white")
    label3.place(relx=.5, rely=.95, anchor="s")
    exitbutton = Button(window, text='Quit!', command=quit,bg="black", fg = "white", font=("Ariel", 20, "bold"))
    exitbutton.place(relx=.15,rely=.95,anchor= "s")
    window.mainloop()
if(x==4):
    window = Tk()
    window.minsize(768,768)
    window.resizable(False,False)
    window.title("Biome Runner")
    photo = PhotoImage(file=f"{x}.png")
    background_label = Label(window, image = photo)
    background_label.pack(fill=BOTH, expand=1)
    label2 = Label(window, text = f"{str4}", font=("Ariel",15,"bold"), anchor="n",bg="black", fg="white")
    label2.place(relx=.5, rely=.2, anchor="s")
    button_next = Button(window, text="Next!", bg="black",font=("Ariel", 20, "bold"), fg="white", command=next)
    button_next.place(relx=.8, rely=.95, anchor="sw")
    label3 = Label(window, text = "Distance remaining: .25 Miles", font=("Ariel",10,"bold"), anchor="n",bg="black", fg="white")
    label3.place(relx=.5, rely=.95, anchor="s")
    exitbutton = Button(window, text='Quit!', command=quit,bg="black", fg = "white", font=("Ariel", 20, "bold"))
    exitbutton.place(relx=.15,rely=.95,anchor= "s")
    
    window.mainloop()
if(x==5):
    window = Tk()
    window.minsize(768,768)
    window.resizable(False,False)
    window.title("Biome Runner")
    photo = PhotoImage(file=f"{x}.png")
    background_label = Label(window, image = photo)
    background_label.pack(fill=BOTH, expand=1)
    label2 = Label(window, text = f"{str5}",font=("Ariel",15,"bold"), anchor="n",bg="black", fg="white")
    label2.place(relx=.5, rely=.2, anchor="s")
    button_next = Button(window, text="Next!", bg="black",font=("Ariel", 20, "bold"), fg="white", command=next)
    button_next.place(relx=.8, rely=.95, anchor="sw")
    label3 = Label(window, text = "Distance remaining: .25 Miles", font=("Ariel",10,"bold"), anchor="n",bg="black", fg="white")
    label3.place(relx=.5, rely=.95, anchor="s")
    exitbutton = Button(window, text='Quit!', command=window.destroy,bg="black", fg = "white", font=("Ariel", 20, "bold"))
    exitbutton.place(relx=.15,rely=.95,anchor= "s")
    window.mainloop()
if(x==6):
    window = Tk()
    window.minsize(768,768)
    window.resizable(False,False)
    window.title("Biome Runner")
    photo = PhotoImage(file=f"{x}.png")
    background_label = Label(window, image = photo)
    background_label.pack(fill=BOTH, expand=1)
    label2 = Label(window, text = f"{str6}", font=("Ariel",15,"bold"), anchor="n",bg="black", fg="white")
    label2.place(relx=.5, rely=.2, anchor="s")
    label3 = Label(window, text = "Distance remaining: .25 Miles", font=("Ariel",10,"bold"), anchor="n",bg="black", fg="white")
    label3.place(relx=.5, rely=.95, anchor="s")
    exitbutton = Button(window, text='Quit!', command=quit,bg="black", fg = "white", font=("Ariel", 20, "bold"))
    exitbutton.place(relx=.5,rely=.95,anchor= "s")
    window.mainloop()